projects:
  hydratrackfrontend:
    schemaPath: src/graphql/schema.json
    includes:
      - 'no'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
